rust-embedded/embedonomicon

- src/preface.md
We implicitly assume Linux as the user's host OS here, right? If so, we should maybe mention that in under `Requirements`.
> review preface

- CNAME
As mentioned in [rust-lang-nursery/embedded-wg#145](https://github.com/rust-lang-nursery/embedded-wg/pull/145)
Added a CNAME file, this requires related A records to take effect.
See https://help.github.com/articles/setting-up-an-apex-domain/ for domain setup, needs at least 2x DNS A records for `embedonomicon` on `rust-embedded.org` pointing to `185.199.108.153` and `185.199.109.153` to become active (4x A records as in the instructions if you feel like it).
> Relocate to https://embedonomicon.rust-embedded.org

- src/preface.md
I just tested how easy it is to get going from scratch with the current instructions. Turns out it was not that easy and users need to do quite some googling on different errors until they can compile the first time.
Add a more elaborate setup section to resolve that.
Maybe needed for MacOS and Windows too?
> Be more elaborate on toolchain setup (Linux)

- ci/exceptions/app/Cargo.toml
- ci/exceptions/app/src/main.rs
- ci/exceptions/app2/src/main.rs
- ci/exceptions/rt/src/lib.rs
- ci/main/app/Cargo.toml
- ci/main/app2/src/main.rs
- ci/main/app3/src/main.rs
- ci/main/app4/Cargo.toml
- ci/main/app4/src/main.rs
- ci/main/rt/Cargo.toml
- ci/main/rt/src/lib.rs
- ci/main/rt2/src/lib.rs
- ci/memory-layout/src/main.rs
- ci/script.sh
- ci/smallest-no-std/Cargo.toml
- ci/smallest-no-std/src/main.rs
- src/exceptions.md
- src/main.md
- src/memory-layout.md
- src/preface.md
- src/smallest-no-std.md
most code changes are minor
the annoying part of using the 2018 edition right now is that there is no easy
way to create new 2018 project (Cargo still defaults to 2015 projects; see
rust-lang/cargo#5980) and there's no visible documentation on how to move a new
project to the 2018 edition (see rust-lang-nursery/edition-guide#102) so I have
included the required changes in the preface -- I hope people won't miss that
part.
r? @rust-embedded/resources (anyone)
closes #1
> move code to the 2018 edition

- ci/exceptions/app/app.objdump
- ci/install.sh
- ci/script.sh
- src/exceptions.md
- src/main.md
- src/memory-layout.md
- src/preface.md
this commit:
- changes the debugger to GDB since Windows and macOS users reported errors with
LLDB
- adds setup instructions for Windows and macOS
- drops the cargo-edit dependency since it's used only once and lets us simplify
the setup instructions
- adds a note regarding .cargo/config being required in section 3 since some
people missed it while reading section 2
- removes a note about llvm-objdump not working correctly since the problem was
fixed in cargo-binutils v0.1.4
closes #8
closes #7
r? @rust-embedded/resources (anyone)
> LLDB -> GDB; +setup instructions for Windows and mac; -cargo-edit

- ci/script.sh
this catches / prevents build errors in the bookshelf repo like
https://travis-ci.org/rust-embedded/bookshelf/builds/433522599
> run linkchecker simulating the bookshelf layout

- src/preface.md
It looked like the link to the edition guide was missing. But it might have been intentional because the edition guide might be moved to doc.rust-lang.org later on (https://github.com/rust-lang-nursery/edition-guide/issues/76) :-)
> Added missing link to edition 2018 guide

- ci/asm/rt/build.rs
- ci/asm/rt2/build.rs
It's needed when using assembly so it's rebuilt when changed (at least for cc, wasn't able to test the .a way)
> Add `rerun-if-changed` when needed

- src/dma.md
The example code didn't match the text underneath.
> Replace references to foo with start in DMA

- ci/asm/app/release.objdump
- ci/asm/rt/link.x
- ci/exceptions/app/app.objdump
- ci/exceptions/rt/link.x
- ci/logging/app2/dev.objdump
- ci/logging/app3/dev.objdump
- ci/logging/app4/dev.objdump
- ci/main/app/app.objdump
- ci/main/rt/link.x
- ci/main/rt2/link.x
- ci/memory-layout/app.text.objdump
- ci/memory-layout/link.x
- ci/script.sh
- ci/singleton/app/dev.objdump
- src/exceptions.md
- src/smallest-no-std.md
Closes #55 
Based at #54 
If the output of `cargo objdump` changes only with regard to whitespace, it's probably OK to still pass CI. Most readers probably won't even notice whitespace differences in the first place.
The [`diff` documentation](https://www.gnu.org/software/diffutils/manual/html_node/White-Space.html#White-Space) says of whitespace-suppressing options:
> The --ignore-space-change (-b) option is stronger than -E and -Z combined. It ignores white space at line end, and considers all other sequences of one or more white space characters within a line to be equivalent.
This ignores only changes _within_ a line -- changes which span multiple lines (i.e. the addition or removal of whitespace-only lines) will still compare as different. This is a good thing, because there are …
> Ignore whitespace within lines when validating objdump outputs in CI

- ci/asm/rt/build.rs
- ci/asm/rt2/build.rs
- ci/logging/app/src/main.rs
- ci/logging/app3/src/main.rs
- ci/logging/app4/src/main.rs
- ci/logging/log/build.rs
- ci/main/rt/build.rs
Fixes #57 
The build scripts were missing `dyn` on the boxed error type; fixing those is a no-brainer.
Additionally, there were warnings about unused `Result`s in the logging apps. I chose to explicitly ignore them (preserving the precise behavior which before had been implicit). But there might be an argument for `unwrap`ing them instead, or demonstrating more idiomatic error-handling.
In any case, it may be worth adding some discussion about how error handling is basically being ignored here in favor of communicating other concepts. Apologies if it's already there - I'm still working through the book myself.
Would anyone be interested in a section on idiomatic error handling in embedded rust? Is that a better fit for the embedded book rather than the embedonomicon? I'll admit that I …
> Fix warnings in build scripts and examples

- src/dma.md
The section on memory barrier requirements for DMA previously suggested that memory barriers are only required when using the data cache. This is not the complete story, as reordering can still occur in the write buffer.
The details will depend on how the involved memory is marked (Normal/Device/…), but a common case where barriers will be needed on e.g. a STM32H7x3-series chip is when interfacing with the Ethernet DMA engine. Even if the dcache is disabled, a barrier will be needed before updating the DMA tail pointer to ensure the driver's writes to the newly-queued packet buffer and buffer descriptor will be seen by the hardware.
I'm not sure whether a more thorough explanation would be in scope here, since it depends on platform details, but with this change, readers are at least made …
> dma: Mention store-buffer reordering on Cortex-M7

- src/main.md
- src/memory-layout.md
Mostly minor grammar fixes and grammar consistency improvements.
> Grammar fixes

- .github/bors.toml
- .github/workflows/ci.yaml
- ci/asm/app/release.objdump
- ci/asm/app/release.vector_table
- ci/exceptions/app/app.objdump
- ci/exceptions/app/app.vector_table.objdump
- ci/logging/app2/dev.objdump
- ci/logging/app3/dev.objdump
- ci/logging/app4/dev.objdump
- ci/main/app/app.objdump
- ci/main/app4/src/main.rs
- ci/memory-layout/app.text.objdump
- ci/memory-layout/app.vector_table.objdump
- ci/singleton/app/dev.objdump
This was a little boring! There aren't any serious changes except to the exceptions app which has changed around a bit; I haven't thoroughly checked the new assembly but don't have any reason to think it's wrong, just the result of much newer LLVM/Rust.
> Fix CI: regenerate known-good outputs with latest Rust nightly

- src/memory-layout.md
Found a small typo in `memory-layout.md`
``` console
cargo objdump --bin app -- -s -section .vector_table
```
should read
``` console
cargo objdump --bin app -- -s --section .vector_table
```
> Typo in cargo objdump argument

- src/custom-target.md
Found a typo'd link on the custom targets page
> Fix link to LLVM libcalls-sync on custom targets page

- src/memory-layout.md
This instruction does not work
`cargo objdump --bin app -- -d -no-show-raw-insn`
Instead I had to add an extra '-' at the start of `-no-show-raw-insn`
`rustc 1.58.0-nightly`
> Adds an extra '-' to an instruction

- src/asm.md
- src/exceptions.md
- src/main.md
> --no-show-raw-insn with one '-'

- src/preface.md
Hi,
The brew cask command is updated. Will encounter this error when installing the tools.
```bash
$ brew cask install gcc-arm-embedded
Error: `brew cask` is no longer a `brew` command. Use `brew <command> --cask` instead.
```
So this PR mainly just update that specific command for macos.
> update macos homebrew install command

- src/dma.md
This was the result of a discussion with Amanieu at RustWeek. It would be nice to add more details about the planned updates (some ticket for example), and I'm not sure if this is the best place to add it to the embedonomicon. But for now, I think mentioning it here is better than nothing.
> Explain how fences interact with volatile operations
